### ISSUE TITLE
[error][main] Error: Page not found

### ISSUE THREAD

**Issue by MitchK** [CodeboxIDE/codebox#423]
Hi, it's Michael (we've met today).

I've checked out master and built codebox: 

```
$ git clone https://github.com/CodeboxIDE/codebox.git
$ cd ./codebox
$ npm install .
$ grunt
```

No build error, no run error in the first place.
If I call ```http://localhost:8000``` (on an Ubuntu 14.04 Vagrant machine), I get: 

```
Codebox is running at http://localhost:3000
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][socket] info GET /socket/events/info 2ms 200
[log][socket] info GET /socket/events/522/9iknpe0s/websocket 2ms (unfinished)
[log][socket] connection to service 'events'
[log][hooks] call hook  settings.get
[error][main] Error: Page not found
    at /home/vagrant/repos/codebox/lib/index.js:120:17
    at Layer.handle [as handle_request] (/home/vagrant/repos/codebox/node_modules/express/lib/router/layer.js:76:5)
    at trim_prefix (/home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:263:13)
    at /home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:230:9
    at Function.proto.process_params (/home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:305:12)
    at /home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:221:12
    at Function.match_layer (/home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:288:3)
    at next (/home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:182:10)
    at /home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:184:16
    at Function.match_layer (/home/vagrant/repos/codebox/node_modules/express/lib/router/index.js:288:3)
```

The UI still renders. Nice and clean by the way :+1: 

Best regards,
Michael

**Comment by nashlai20** [comment]
i have this problem, any one can help?

![image](https://cloud.githubusercontent.com/assets/7370283/6663300/49cb12ee-cc00-11e4-91ac-1522f61e9d08.png)

**Comment by isc30** [comment]
Same error
