### ISSUE TITLE
Error: Cannot find module 'shux'

### ISSUE THREAD

**Issue by MitchK** [CodeboxIDE/codebox#463]
Hi, I'm trying to get ready for developing an add on for Codebox.

Node version: ```v0.10.32``` Wrong version maybe?

Reproduce issue:
```
$ git clone https://github.com/CodeboxIDE/codebox.git
$ cd ./codebox
$ npm install .
$ grunt
$ node bin/codebox.js 
[log][local] Creating /Users/i841712/.codebox
[log][socket] add service events
[log][events] events are ready
[log][hooks] init hooks
[log][workspace] Working on  /Users/i841712/repos/codebox
[log][events] event 'workspace:ready'
[log][users] init users
[log][rpc] add service fs with 9 methods
[log][rpc] add service packages with 3 methods
[log][rpc] add service users with 2 methods
[log][rpc] add service settings with 2 methods
[log][rpc] add service codebox with 2 methods
[log][packages] Load and prepare packages (14 dependencies)
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][events] event 'packages:add'
[log][package] start editor sync services
[log][socket] add service editorsync
Error: Cannot find module 'shux'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/i841712/repos/codebox/packages/terminal/lib/shells.js:6:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Cheers,
Mitch

**Comment by MitchK** [comment]
After trying multiple Node versions it works with Node.js ```v0.10.26```

**Comment by alxrcs** [comment]
I'm having this issue as well. I've tried with both the latest versions (6.3.0, 4.4.7 LTS) and the ones the issue author mentions to solve the problem (0.10.26).

Any suggestions would be appreciated, I'd really like to try Codebox.

**Comment by oquidave** [comment]
Having the same problem here

**Comment by scrumit** [comment]
Apart from Codebox being abandoned some time ago, [shux]( https://www.npmjs.com/package/shux) is [failing it's build](https://github.com/substack/shux).

In Samy's current project they use [ProseMirror](https://github.com/SamyPesse/prosemirror) which has collaborative editing built in. To me, that implies the Codebox solution wasn't a good one.

The corollary is that if you (we) fix this you may becoming the maintainer for a webIDE.
