### ISSUE TITLE
page not found

### ISSUE THREAD

**Issue by nashlai20** [CodeboxIDE/codebox#477]
hi, I start the codebox, but when I browse, I get "Page not found",  what's the problem?

[error][main] Error: Page not found
    at /usr/local/codebox/lib/index.js:120:17
    at Layer.handle [as handle_request] (/usr/local/codebox/node_modules/express/lib/router/layer.js:76:5)
    at trim_prefix (/usr/local/codebox/node_modules/express/lib/router/index.js:263:13)
    at /usr/local/codebox/node_modules/express/lib/router/index.js:230:9
    at Function.proto.process_params (/usr/local/codebox/node_modules/express/lib/router/index.js:305:12)
    at /usr/local/codebox/node_modules/express/lib/router/index.js:221:12
    at Function.match_layer (/usr/local/codebox/node_modules/express/lib/router/index.js:288:3)
    at next (/usr/local/codebox/node_modules/express/lib/router/index.js:182:10)
    at /usr/local/codebox/node_modules/express/lib/router/index.js:184:16
    at Function.match_layer (/usr/local/codebox/node_modules/express/lib/router/index.js:288:3)

**Comment by isc30** [comment]
same problem

**Comment by johnjelinek** [comment]
Duplicate of #423

**Comment by johnjelinek** [comment]
For reference:
```
Codebox is running at http://localhost:3000
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][hooks] call hook  users.auth
[log][events] event 'users:add'
[log][socket] info GET /socket/events/info 1ms 200
[log][socket] info GET /socket/events/411/_wz14qic/websocket 2ms (unfinished)
[log][socket] connection to service 'events'
[log][hooks] call hook  settings.get
[error][main] Error: Page not found
    at /usr/src/app/lib/index.js:120:17
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:76:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:263:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:230:9
    at Function.proto.process_params (/usr/src/app/node_modules/express/lib/router/index.js:305:12)
    at /usr/src/app/node_modules/express/lib/router/index.js:221:12
    at Function.match_layer (/usr/src/app/node_modules/express/lib/router/index.js:288:3)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:182:10)
    at /usr/src/app/node_modules/express/lib/router/index.js:184:16
    at Function.match_layer (/usr/src/app/node_modules/express/lib/router/index.js:288:3)
[log][socket] info GET /socket/terminal/info 0ms 200
[log][socket] info GET /socket/terminal/711/0bued6xv/websocket 1ms (unfinished)
[log][socket] connection to service 'terminal'
[log][package] open shell  { shellId: 'term536-25',
  opts: { rows: 80, columns: 24, id: 'term536-25', cwd: null } }
[log][events] event 'shell.spawn'
[log][events] event 'shell.attach'
[log][events] event 'shell.open'
[log][events] event 'shell.resize'
[log][events] event 'shell.exit'

/usr/src/app/packages/terminal/node_modules/shux/node_modules/pty.js/lib/pty.js:286
  return this.socket.emit.apply(this.socket, arguments);
                          ^
RangeError: Maximum call stack size exceeded
```

Everything appears to work though. Maybe it should be a `WARN`.

**Comment by johnjelinek** [comment]
Here's a Dockerfile I'm using to test with:
```
FROM node:0.10-onbuild

RUN groupadd user && useradd --create-home --home-dir /home/user -g user user
RUN chown -R user:user /usr/src/app

RUN npm install -g grunt-cli
RUN grunt

EXPOSE 3000
CMD ["su", "-", "user", "-c", "/usr/src/app/bin/codebox.js"]
```

**Comment by nashlai20** [comment]
My problem seem to be different as yours, I confused with what it happend. 

![image](https://cloud.githubusercontent.com/assets/7370283/6705523/9e0dd44a-cd90-11e4-9480-41e65256d6f5.png)

**Comment by isc30** [comment]
I think its the same problem xD

**Comment by nashlai20** [comment]
@isc30, what can I do to resolve it?

**Comment by isc30** [comment]
I dont know, finally i got the 0.8.x branch and 0 errors installing it
You can "npm install -g codebox" directly

**Comment by isc30** [comment]
Cloud9 released alpha version few days ago, it works perfect with nodejs v0.10.36
https://github.com/c9/core

**Comment by aaronbartell** [comment]
Was anyone able to find a solution to this issue?

**Comment by train860** [comment]
same problem
