### ISSUE TITLE
Installation succeeds, but running fails

### ISSUE THREAD

**Issue by ghost** [CodeboxIDE/codebox#514]
- npm: `3.3.12`
- node: `v5.1.1`

---

EDIT:
system(s):
- `Ubuntu 15.10` x86_64
- `Raspbian` ARMv6

---

Running `codebox run ~/workspace` initiates the package installation, but when that's done I get the following error:

```
[log][events] event 'packages:add'
[log][package] start run services
[log][rpc] add service project with 2 methods
Error: Cannot find module 'shux'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/conmarap/.codebox/packages/terminal/lib/shells.js:6:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

While digging deeper I noticed that every dependency of the `terminal` module was a broken linked file. Even when I tried installing them manually it was impossible to get codebox to work.

**Comment by AmreeshTyagi** [comment]
I am also facing the same issue.
Codebox: v1.0.0-aplha.5
Node: v4.2.6 (LTS)
Npm: v2.14.12

**Comment by TylerJewell** [comment]
It doesn't seem like Codebox is being maintained much.  You may want to consider [Eclipse Che](www.eclipse.org/che), which is an open source project working on similar concepts.

**Comment by ksmanu** [comment]
Though it is really *insane* trying to contact you guys, but has anyone solved the installation hurdles. Is there any group about it?
